M48
; DRILL file {KiCad 7.0.7} date Tue Mar 19 14:26:35 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-19T14:26:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X114.39Y-57.511
X114.39Y-63.291
T2
X157.656Y-57.39
X164.656Y-57.39
T3
X113.0Y-68.5
T0
M30
