M48
; DRILL file {KiCad 7.0.7} date Thu Feb  8 13:52:20 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-08T13:52:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X4.4783Y-2.2602
X4.4783Y-2.4878
T2
X6.2157Y-2.3319
X6.4913Y-2.3319
T3
X4.4488Y-2.6969
X6.3386Y-2.6969
T0
M30
